# Generated by Django 4.1.2 on 2023-05-31 07:23

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov_name', models.CharField(max_length=250)),
                ('mov_desc', models.TextField()),
                ('mov_cat', django_mysql.models.ListTextField(models.CharField(max_length=100), size=3)),
                ('mov_trailer', models.TextField()),
                ('mov_img', models.ImageField(default='', upload_to='images')),
                ('mov_poster', models.ImageField(default='', upload_to='posters')),
                ('mov_vid', models.FileField(upload_to='vid')),
            ],
        ),
    ]
