# Generated by Django 4.1.2 on 2023-06-12 16:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_mov_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_name', models.CharField(max_length=250)),
                ('ser_desc', models.TextField()),
                ('ser_cat', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=120, size=3)),
                ('ser_trailer', models.TextField()),
                ('ser_img', models.ImageField(default='', upload_to='images')),
                ('ser_poster', models.ImageField(default='', upload_to='posters')),
                ('ser_vid', models.FileField(upload_to='servid')),
            ],
        ),
    ]
